# Generated by Django 6.0.6 on 2026-06-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('Informatica', 'Informática'), ('Exatas', 'Exatas'), ('Engenharia', 'Engenharia')], default='Informatica', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinguagemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='TecnologiaFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('dados_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('dados_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('carga_horaria', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_vaga', models.CharField(choices=[('Estágio', 'Estágio'), ('Iniciação Científica', 'Iniciação Científica (IC)'), ('Trainee', 'Trainee')], default='Estágio', max_length=50)),
                ('modalidade', models.CharField(choices=[('Presencial', 'Presencial'), ('Híbrido', 'Híbrido'), ('Remoto', 'Remoto')], default='Presencial', max_length=50)),
                ('salario', models.CharField(blank=True, max_length=100)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('prazo_candidatura', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cr', models.CharField(blank=True, max_length=20)),
                ('periodo_minimo', models.IntegerField(blank=True, null=True)),
                ('periodo_maximo', models.IntegerField(blank=True, null=True)),
                ('arquivo_vaga', models.FileField(blank=True, null=True, upload_to='vagas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('areas_atuacao', models.ManyToManyField(blank=True, to='usuarios.areaatuacao')),
                ('cursos', models.ManyToManyField(blank=True, related_name='vagas', to='usuarios.curso')),
                ('linguagens', models.ManyToManyField(blank=True, to='usuarios.linguagemprogramacao')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas', to='usuarios.localizacao')),
                ('professor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_publicadas', to='usuarios.professor')),
                ('tecnologias', models.ManyToManyField(blank=True, to='usuarios.tecnologiaframework')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxilios', models.TextField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_vaga', models.CharField(max_length=50)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('cr', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=30)),
                ('periodo', models.IntegerField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='alunos/curriculos/')),
                ('tipo_interesse', models.CharField(choices=[('estagio', 'Estágio'), ('ic', 'Iniciação Científica (IC)'), ('ambos', 'Ambos')], max_length=20, null=True)),
                ('areas_atuacao', models.ManyToManyField(blank=True, to='usuarios.areaatuacao')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='usuarios.curso')),
                ('linguagens', models.ManyToManyField(blank=True, to='usuarios.linguagemprogramacao')),
                ('tecnologias', models.ManyToManyField(blank=True, to='usuarios.tecnologiaframework')),
                ('dados_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('vagas_salvas', models.ManyToManyField(blank=True, related_name='alunos_favoritaram', to='usuarios.vaga')),
            ],
        ),
    ]
