# Generated by Django 6.0.5 on 2026-05-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagio',
            name='vaga',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cpf',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='beneficios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='carga_horaria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='periodo_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Bolsa',
        ),
        migrations.DeleteModel(
            name='Estagio',
        ),
    ]
