# Generated by Django 6.0.5 on 2026-05-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_estagio_vaga_remove_funcionario_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
