# Generated by Django 6.0.6 on 2026-06-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_vaga_local_delete_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='codigo_identificacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='sobre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='disciplina',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
