# Generated by Django 6.0.5 on 2026-05-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_aluno_cpf_alter_aluno_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='disciplina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
