# Generated by Django 6.0.5 on 2026-06-16 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_professor_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='beneficios',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='periodo_min',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='valor',
        ),
        migrations.AddField(
            model_name='vaga',
            name='arquivo_vaga',
            field=models.FileField(blank=True, null=True, upload_to='vagas/'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='cr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vaga',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='cursos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vaga',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='local',
            field=models.CharField(default='Não informado', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='modalidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vaga',
            name='periodo_maximo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vaga',
            name='periodo_minimo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vaga',
            name='prazo_candidatura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='salario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vaga',
            name='titulo',
            field=models.CharField(default='Não informado', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaga',
            name='carga_horaria',
            field=models.CharField(blank=True, default='Não informado', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaga',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.CharField(default='Não informado', max_length=100),
            preserve_default=False,
        ),
    ]
