# Generated by Django 6.0.5 on 2026-06-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_professor_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('informatica', 'Informática'), ('exatas', 'Exatas'), ('engenharia', 'Engenharia')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LinguagemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='tipo_interesse',
            field=models.CharField(choices=[('estagio', 'Estágio'), ('ic', 'Iniciação Científica (IC)'), ('ambos', 'Ambos')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(default='Indefinido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='genero',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default='0000000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='periodo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='areas_atuacao',
            field=models.ManyToManyField(blank=True, to='usuarios.areaatuacao'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='linguagens',
            field=models.ManyToManyField(blank=True, to='usuarios.linguagemprogramacao'),
        ),
    ]
