# Generated by Django 6.0.5 on 2026-06-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_areaatuacao_linguagemprogramacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnologiaFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, to='usuarios.tecnologiaframework'),
        ),
    ]
