# Generated by Django 6.0.5 on 2026-06-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_tecnologiaframework_alter_aluno_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaatuacao',
            name='categoria',
            field=models.CharField(choices=[('Informatica', 'Informática'), ('Exatas', 'Exatas'), ('Engenharia', 'Engenharia')], default='Informatica', max_length=50),
        ),
        migrations.AlterField(
            model_name='areaatuacao',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
