# Generated by Django 6.0.5 on 2026-06-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_areaatuacao_categoria_alter_areaatuacao_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='beneficios',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='periodo_min',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='valor',
        ),
        migrations.AddField(
            model_name='vaga',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='vagas/anexos/'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='areas_atuacao',
            field=models.ManyToManyField(blank=True, to='usuarios.areaatuacao'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='curso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='linguagens',
            field=models.ManyToManyField(blank=True, to='usuarios.linguagemprogramacao'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='periodo_minimo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, to='usuarios.tecnologiaframework'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='titulo',
            field=models.CharField(default='Vaga Antiga', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaga',
            name='carga_horaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.CharField(default='Estágio', max_length=50),
            preserve_default=False,
        ),
    ]
