# Generated by Django 6.0.5 on 2026-06-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_vaga_beneficios_remove_vaga_instituicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='alunos/curriculos/'),
        ),
    ]
