# Generated by Django 6.0.5 on 2026-06-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_aluno_curriculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='vagas_salvas',
            field=models.ManyToManyField(blank=True, related_name='alunos_favoritaram', to='usuarios.vaga'),
        ),
    ]
